
export const formalProducts = [
    {
        cat:"formal",
        id:1,
        img:require('./Pictures/Formal/1.jpg').default,
        desc:"PREMIER LADIES LONG SLEEVE SHIRT NATURAL",
        price:15.00,
    },
    {
        cat:"formal",
        id:2,
        img:require ('./Pictures/Formal/2.webp').default,
        desc:"Navy Blue Tailored Straight Leg Trousers",
        price:26,
    },
    {
        cat:"formal",
        id:3,
        img:require('./Pictures/Formal/3.webp').default,
        desc:" Ladies Regular Fit Black Skirt",
        price:19,
    },
    {
        cat:"formal",
        id:4,
        img:require('./Pictures/Formal/4.jpg').default,
        desc:"Ladies Premium Oxford Short Sleeved Blouse",
        price:15,
    },
    {
        cat:"formal",
        id:5,
        img:require('./Pictures/Formal/5.jpg').default,
        desc:"Women's 2 Piece Suit - Green ",
        price:45,
    },
    {
        cat:"formal",
        id:6,
        img:require('./Pictures/Formal/6.jpg').default,
        desc:"Womens Formal Long Sleeve Lace Patchwork Tops",
        price:12,
    },
    {
        cat:"formal",
        id:7,
        img:require('./Pictures/Formal/7.webp').default,
        desc:"PLEAT FRONT BELTED TAILORED MIDI DRESS",
        price:68,
    },
    {
        cat:"formal",
        id:8,
        img:require('./Pictures/Formal/8.jpg').default,
        desc:"Black Pencil cut formal dress",
        price:50,
    },  
    {
        cat:"formal",
        id:9,
        img:require('./Pictures/Formal/9.webp').default,
        desc:"Black High Waist Slim Stretch Trousers",
        price:8,
    },  
    {
        cat:"formal",
        id:10,
        img:require('./Pictures/Formal/10.jpg').default,
        desc:"Womens Open Front Blazers formal Long Sleeve Orange",
        price:30,
    },  
    {
        cat:"formal",
        id:"11",
        img:require('./Pictures/Formal/11.jpg').default,
        desc:"Formal Long Sleeve Blazer Pink",
        price:38,
    },  
    {
        cat:"formal",
        id:"12",
        img:require('./Pictures/Formal/12.jpg').default,
        desc:"Women's 2 Pieces Suit - APRICOT ",
        price:45,
    },  
    
]

export const casualProducts = [ 
    {
        cat:"casual",
        id:1,
        img:require('./Pictures/Casual/1.webp').default,
        desc:"Ditsy Floral Print Short Sleeve Midi Dress",
        price:35,
    },
    {
        cat:"casual",
        id:2,
        img:require('./Pictures/Casual/2.jpg').default,
        desc:"Blue Stripe Soft Fine Knit Long Top",
        price:15.99,
    },
    {
        cat:"casual",
        id:3,
        img:require('./Pictures/Casual/3.jpg').default,
        desc:"Womens Crochet Trim Top White",
        price:10,
    },
    {
        cat:"casual",
        id:4,
        img:require('./Pictures/Casual/4.webp').default,
        desc:"Women's Tank Top Sleeveless PINK",
        price:12.99,
    },
    {
        cat:"casual",
        id:5,
        img:require('./Pictures/Casual/5.jpg').default,
        desc:"Blue Elasticated Hem Crinkle Blouse",
        price:25.99,
    },
    {
        cat:"casual",
        id:6,
        img:require('./Pictures/Casual/6.jpg').default,
        desc:"Satin Pleat Pull-On Print Skirt",
        price:28,
    },
    {
        cat:"casual",
        id:7,
        img:require('./Pictures/Casual/7.jpg').default,
        desc:"Maxi Shirt Dress - Soft Fern",
        price:45,
    },
    {
        cat:"casual",
        id:8,
        img:require('./Pictures/Casual/8.jpg').default,
        desc:"Chiffon Shirred Long Sleeve Blouse",
        price:31,
    },
    {
        cat:"casual",
        id:9,
        img:require('./Pictures/Casual/9.jpg').default,
        desc:"Relaxed Slim Leg Jeans",
        price:26.99,
    },
    {
        cat:"casual",
        id:10,
        img:require('./Pictures/Casual/10.jpg').default,
        desc:"Cotton Pull-On Crop Trousers",
        price:15,
    },
    {
        cat:"casual",
        id:11,
        img:require('./Pictures/Casual/11.jpg').default,
        desc:"Full Bloom Print Jersey Midi Dress ",
        price:31,
    },
    {
        cat:"casual",
        id:12,
        img:require('./Pictures/Casual/12.jpg').default,
        desc:"Organic Cotton Jog Pants",
        price:22,
    },
]

export const knitProducts = [
    {
        cat:"knit",
        id:1,
        img:require('./Pictures/Knitwear/1.jpg').default,
        desc:"Long Sleeve Cable Button Cardigan",
        price:30,
    },
    {
        cat:"knit",
        id:2,
        img:require('./Pictures/Knitwear/2.jpg').default,
        desc:"Crew Neck Stripe Cotton Jumper",
        price:24,
    },
    {
        cat:"knit",
        id:3,
        img:require('./Pictures/Knitwear/3.jpg').default,
        desc:"Textured Cotton Crew Neck Jumper",
        price:"£26",
    },
    {
        cat:"knit",
        id:4,
        img:require('./Pictures/Knitwear/4.jpg').default,
        desc:"Fleece Trim Cardigan",
        price:20,
    },
    {
        cat:"knit",
        id:5,
        img:require('./Pictures/Knitwear/5.jpg').default,
        desc:"Prettiest Embroidered Sleeve Jumper",
        price:31,
    },
    {
        cat:"knit",
        id:6,
        img:require('./Pictures/Knitwear/6.jpg').default,
        desc:"Tactile Hooded Knitted Zip Cardigan",
        price:40,
    },
    {
        cat:"knit",
        id:7,
        img:require('./Pictures/Knitwear/7.jpg').default,
        desc:"Two-Tone Longline Coatigan",
        price:45,
    },
    {
        cat:"knit",
        id:8,
        img:require('./Pictures/Knitwear/8.jpg').default,
        desc:"Cotton Cable Stripe Crew Neck Jumper",
        price:28,
    },
]

export const jacketProducts = [
    {
        cat:"jacket",
        id:1,
        img:require('./Pictures/Jackets/1.jpg').default,
        desc:"The Sherpa Collar Denim Jacket",
        price:30,
    },
    {
        cat:"jacket",
        id:2,
        img:require('./Pictures/Jackets/2.jpg').default,
        desc:"Right-As-Rain Waterproof Fleece Lined Jacket",
        price:55,
    },
    {
        cat:"jacket",
        id:3,
        img:require('./Pictures/Jackets/3.jpg').default,
        desc:"Cooler Days Quilted Jacket",
        price:49.99,
    },
    {
        cat:"jacket",
        id:4,
        img:require('./Pictures/Jackets/4.jpg').default,
        desc:"Floral Print Quilted Jacket",
        price:60,
    },
    {
        cat:"jacket",
        id:5,
        img:require('./Pictures/Jackets/5.jpg').default,
        desc:"Padded Hooded Coat",
        price:65,
    },
    {
        cat:"jacket",
        id:6,
        img:require('./Pictures/Jackets/6.jpg').default,
        desc:"Chic Faux Leather Jacket",
        price:27,
    },
    {
        cat:"jacket",
        id:7,
        img:require('./Pictures/Jackets/9.jpg').default,
        desc:"Bonded Fleece Coat",
        price:42,
    },
    {
        cat:"jacket",
        id:8,
        img:require('./Pictures/Jackets/8.jpg').default,
        desc:"Faux Shearling Coat",
        price:40,
    },
    
]